# Generated by Django 3.1.6 on 2021-02-18 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='email_address',
        ),
    ]
